// ================================
// Maintix Shared Enums
// ================================

export enum Role {
  TENANT = 'TENANT',
  MANAGER = 'MANAGER',
  TECHNICIAN = 'TECHNICIAN',
}

export enum TicketStatus {
  OPEN = 'OPEN',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  DONE = 'DONE',
  CANCELLED = 'CANCELLED',
}

export enum Priority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum ActivityAction {
  TICKET_CREATED = 'TICKET_CREATED',
  TECHNICIAN_ASSIGNED = 'TECHNICIAN_ASSIGNED',
  TECHNICIAN_REASSIGNED = 'TECHNICIAN_REASSIGNED',
  WORK_STARTED = 'WORK_STARTED',
  COMPLETION_SUBMITTED = 'COMPLETION_SUBMITTED',
  TICKET_APPROVED = 'TICKET_APPROVED',
  TICKET_CANCELLED = 'TICKET_CANCELLED',
  PRIORITY_CHANGED = 'PRIORITY_CHANGED',
  ATTACHMENT_ADDED = 'ATTACHMENT_ADDED',
  ATTACHMENT_REMOVED = 'ATTACHMENT_REMOVED',
}

export enum NotificationType {
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  WORK_STARTED = 'WORK_STARTED',
  COMPLETION_SUBMITTED = 'COMPLETION_SUBMITTED',
  TICKET_APPROVED = 'TICKET_APPROVED',
  TICKET_CANCELLED = 'TICKET_CANCELLED',
  PRIORITY_CHANGED = 'PRIORITY_CHANGED',
  TECHNICIAN_REASSIGNED = 'TECHNICIAN_REASSIGNED',
}
