// ================================
// Maintix Error Codes
// ================================

export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_INACTIVE = 'USER_INACTIVE',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  WRONG_PASSWORD = 'WRONG_PASSWORD',

  // Authorization
  FORBIDDEN = 'FORBIDDEN',
  ROLE_NOT_ALLOWED = 'ROLE_NOT_ALLOWED',
  PROPERTY_ACCESS_DENIED = 'PROPERTY_ACCESS_DENIED',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  CANNOT_CREATE_MANAGER = 'CANNOT_CREATE_MANAGER',

  // Properties
  PROPERTY_NOT_FOUND = 'PROPERTY_NOT_FOUND',
  ALREADY_PROPERTY_MEMBER = 'ALREADY_PROPERTY_MEMBER',
  NOT_PROPERTY_MEMBER = 'NOT_PROPERTY_MEMBER',

  // Categories
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_NAME_EXISTS = 'CATEGORY_NAME_EXISTS',

  // Tickets
  TICKET_NOT_FOUND = 'TICKET_NOT_FOUND',
  TICKET_INVALID_TRANSITION = 'TICKET_INVALID_TRANSITION',
  TICKET_VERSION_CONFLICT = 'TICKET_VERSION_CONFLICT',
  TICKET_NOT_CANCELLABLE = 'TICKET_NOT_CANCELLABLE',
  TECHNICIAN_NOT_ASSIGNEE = 'TECHNICIAN_NOT_ASSIGNEE',
  ASSIGNEE_NOT_TECHNICIAN = 'ASSIGNEE_NOT_TECHNICIAN',
  ASSIGNEE_NOT_PROPERTY_MEMBER = 'ASSIGNEE_NOT_PROPERTY_MEMBER',

  // Uploads
  UPLOAD_SIZE_EXCEEDED = 'UPLOAD_SIZE_EXCEEDED',
  UPLOAD_TYPE_NOT_ALLOWED = 'UPLOAD_TYPE_NOT_ALLOWED',
  UPLOAD_LIMIT_REACHED = 'UPLOAD_LIMIT_REACHED',
  ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
